version: '3'
services:
  dev-consul-01:
    image:  consul:1.0.2
    command: [ "consul", "agent","-server","-recursor","8.8.8.8","-bootstrap-expect=1","-ui" ]
    deploy:
      restart_policy:
        condition: on-failure
    ports:
     - "8300:8300"
     - "8301:8301"
     - "8302:8302"
     - "8400:8400"
     - "8500:8500"
     - "8600:8600"
    volumes:
      - ./data:/consul/data
    networks:
      - demo-net
networks:
  demo-net:
    driver:  overlay
